### ISSUE TITLE
I can’ t find the latest dock FW in Fedora 36 + Fwupd V1.7.7

### ISSUE THREAD

**Issue by gaby-xie** [fwupd/firmware-hp#1]
**Describe the bug**
I can’ t find the latest dock FW in Fedora 36 + Fwupd V1.7.7

**Steps to Reproduce**
1.	Install Fedora OS 36 and update to the latest. Gnome-firmware is 42.1
2.	Install fwupd V1.7.7.
3.	Connect HP USB-C Dock G5 to host.
4.	Open gnome-firmware.
5.	There is only previous FW version show in gnome-firmware. But no the latest FW V1.0.15.0.
6.	Double check with Ubuntu OS V22.04+Fwupd V1.7.5+gnome-firmware V42.0, I can find the latest FW V1.0.15.0.

**Expected behavior**
I can find the latest dock FW in both Fedora and Ubuntu.

**fwupd version information**
V1.7.7.

**Comment by hughsie** [comment]
There's new firmware in the lvfs-testing remote if that helps.

**Comment by chlee75** [comment]
@gaby-xie 

I checked G5 and G2 dock firmware state in the LVFS.
For G5, V1.0.11.0, 1.0.13.0,1.0.14.0,1.0.15.0 are in the testing state.
For G2, V1.1.14.0 is in the testing state and V1.1.13.0 is in the stable state.

I installed Ubuntu 22.04 and tested G5 dock in gnome-firmware. No firmware available. It is expected.
I have not tested G2 because I don't have it. But I expect that  V1.1.13.0 is available for G2.

If your Ubuntu uses fwupd in embargo, then All G5 and G2 firmware can be seen in gnome-firmware.

If you expect the same result in Fedora which use official fwupd, then uninstall fwupd in embargo and reinstall official fwupd.
If it is hard to uninstall fwupd in embargo and reinstall official fwupd, please reinstall Ubuntu and test it.

With official fwupd in Ubunu, it is expected that No firmware is available for G5 and  V1.1.13.0 is available in G2.

Thanks.

**Comment by gaby-xie** [comment]
@chlee75 

Thanks!
After I run below command and delete hp-ws-embargo.conf from remotes.d folder. I can only find G2 dock OCI V1.1.13.0 in gnome-firmware. It’s excepted behavior due to only OCI V1.1.13.0 is stable state.
This is not a real issue. So I will close it. Thanks!

$fwupdmgr --force refresh
Run gnome-firmware
